export const userData = {
    education: 'Bachelor of Science in Computer Science',
    isEmailVerified: true,
    uid: '3lYQLGudEWRrEM22DfGWCOgUKC93',
    permissions: {
        add_new_hr_page_item: true,
        show_cto_voucher_requests: true,
        show_manage_page: true,
        allow_revert: false,
        show_projects_page: true,
        allow_edit_project: true,
        allow_add_new_employee: true,
        allow_add_project: true,
        add_news_from_hr_page: true,
        show_leaves: true,
        allow_edit_permissions: true,
        allow_edit_employee: true,
    },
    activeApplication: 'Leave Application',
    email: 'johndoe@example.com',
    leavingDate: null,
    lastOffDate: null,
    creationDate: '2024-08-22T12:00:00Z',
    activeApplicationType: 'Leave',
    function: 'Software Engineer',
    isAfk: false,
    lineManager: {
        uid: 'manager123',
        profilePicture: 'https://example.com/path/to/profile.jpg',
        name: 'Jane Smith',
        department: 'Engineering',
        title: 'Senior Manager',
        email: 'janesmith@example.com',
    },
    address: '123 Main St, Anytown, USA',
    gender: 'Male',
    employmentType: 'Full-time',
    joiningDate: '2023-01-15T00:00:00Z',
    lineManagerId: 'manager123',
    title: 'Software Engineer',
    hasPendingLeaveApplication: false,
    currentLocation: 'Remote',
    profilePicture: 'https://example.com/path/to/profile-picture.jpg',
    isWfh: true,
    phone: '555-1234',
    dob: '1990-04-25T00:00:00Z',
    name: 'John Doe',
    department: 'Engineering',
    isProfileSetup: true,
    userType: 1,
    level: 'L3',
    subLevel: 'L3.2',
    promotionHistory: [],
    incrementHistory: [
        { _seconds: 1609459200, _nanoseconds: 0 },
        { _seconds: 1672444800, _nanoseconds: 0 },
    ],
    IAHistory: [
        { _seconds: 1672444800, _nanoseconds: 0 },
    ],
    leaves: {
        medical: 10,
        paternity: 5,
        wedding: 0,
        bdo: 2,
        cto: 10,
        pto: 20,
    },
};